### ISSUE TITLE
Dependency on vue-template-compiler

### ISSUE THREAD

**Issue by mimecorg** [vuejs/component-compiler-utils#11]
The component-compiler-utils module requires vue-template-compiler, but it's not listed as a dependency (only a dev dependency). When I use vue-loader with a custom template compiler, and I don't install vue-template-compiler, I get an error.

Of course as a workaround I can install vue-template-compiler manually. But in that case I end up having three template compilers installed: vue-template-compiler, vue-template-es2015-compiler and my custom template compiler. Is that intentional?

**Comment by znck** [comment]
It requires `vue-template-compiler` as a peer dependency. Though it is missing from package.json, that is certainly unintended.

**Comment by ishitatsuyuki** [comment]
@znck Do you know if this should be better a normal dependency, or a peerDependency?

**Comment by znck** [comment]
It should be a peer as it’s  version should match with the locally installed Vue version.
