### ISSUE TITLE
Problem with `prettier@3`

### ISSUE THREAD

**Issue by ThornWalli** [vuejs/component-compiler-utils#133]
Hello, 

just trying to get a `nuxt@2` running with a current `eslint` configuration.

I get an error:

![image](https://github.com/vuejs/component-compiler-utils/assets/8287751/d03ad90a-a9db-4abe-a0a5-be4b64b2e430)

I could trace it back to the installation of `prettier@3`. 
There seems to be a conflict with this dependency because it requires `prettier@2`.

I tried to solve it with an `override` in the `package.json`. Unfortunately without success. 

```json
{
  "overrides": {
    "@vue/component-compiler-utils": {
      "prettier": "2.8.8"
    }
  }
}
```

**Comment by eltongarbin** [comment]
I solved updating to false the prettify option from vue-loader:

> [...] if you encounter any obscure bug of prettier [...] you can disable this option to circumvent it.
https://vue-loader.vuejs.org/options.html#prettify

**Comment by ThornWalli** [comment]
Very good, thank you!
