### ISSUE TITLE
prettier remove default parser breaks the tool

### ISSUE THREAD

**Issue by pwang2** [vuejs/component-compiler-utils#14]
In prettier 1.13.0, default parser was removed with a minor version(used to be babylon), this breaks the formatter here.

https://github.com/vuejs/component-compiler-utils/blob/8a8a95c84dc2f3f14625e31805f975d11a898990/lib/compileTemplate.ts#L161

Issue has been created in prettier repo as well, attached here for tracking purpose. 
https://github.com/prettier/prettier/issues/4567

Adding error stack info below for our friend Google to route new comers to:

```
ERROR in ./src/client/components/Com1.vue?vue&type=template&id=22d07c36 (../happy-cli/node_modules/vue-loader/lib/loaders/templateLoader.js??vue-loader-options!../happy-cli/node_modules/vue-loader/lib??vue-loader-options!./src/client/components/Com1.vue?vue&type=template&id=22d07c36)

Module build failed: Error: No parser and no file path given, couldn't infer a parser.
    at normalize ({project_dir}/node_modules/prettier/index.js:7051:13)
    at formatWithCursor ({project_dir}/node_modules/prettier/index.js:10370:12)
    at {project_dir}/node_modules/prettier/index.js:31115:15
    at Object.format ({project_dir}/node_modules/prettier/index.js:31134:12)
    at actuallyCompile ({project_dir}/node_modules/@vue/component-compiler-utils/dist/compileTemplate.js:93:29)
    at compileTemplate ({project_dir}/node_modules/@vue/component-compiler-utils/dist/compileTemplate.js:26:16)
    at Object.module.exports ({project_dir}/node_modules/vue-loader/lib/loaders/templateLoader.js:42:20)
```

PR: https://github.com/vuejs/component-compiler-utils/pull/15

**Comment by Tarpsvo** [comment]
Damn. Just decided to try thevue-cli out and ended up with the no parser error. I was at a complete loss, but managed to dig my way through the prettier breaking change. Good job finding a solution this quick and thanks, implemented this locally. 👍

**Comment by lanxin1234** [comment]
in ./src/App.vue

Module build failed: Error: No parser and no file path given, couldn't infer a parser.
    at normalize (/Users/lanc/Desktop/runbuild/node_modules/_prettier@1.13.0@prettier/index.js:7051:13)
    at formatWithCursor (/Users/lanc/Desktop/runbuild/node_modules/_prettier@1.13.0@prettier/index.js:10370:12)
    at /Users/lanc/Desktop/runbuild/node_modules/_prettier@1.13.0@prettier/index.js:31115:15
    at Object.format (/Users/lanc/Desktop/runbuild/node_modules/_prettier@1.13.0@prettier/index.js:31134:12)
    at Object.module.exports (/Users/lanc/Desktop/runbuild/node_modules/_vue-loader@13.7.1@vue-loader/lib/template-compiler/index.js:80:23)

 @ ./src/App.vue 11:0-392
 @ ./src/main.js
 @ multi ./node_modules/_webpack-dev-server@2.11.2@webpack-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main.js

**Comment by lanxin1234** [comment]
How to solve this?

**Comment by pwang2** [comment]
in your package.json, force prettier to be 1.12 with
```sh
npm install prettier@~1.12.1
```

**Comment by lovemyliwu** [comment]
@pwang2 not work, still get 1.13.0
`npm view prettier version`

**Comment by pwang2** [comment]
@lovemyliwu if you are using customized tools or npm link, it might be tricky and requires you to target the package tree correctly.

You might also need to regenerate you pacakge-lock.json or yarn.lock file.

**Comment by pwang2** [comment]
Merged.  

Thanks @yyx990803 !  We could expect an new version of @vue/component-compiler-utils soon.

**Comment by yyx990803** [comment]
Released in 1.3.1

**Comment by chengzhuotc** [comment]
我还是不可以啊，该怎么弄

**Comment by yyx990803** [comment]
remove `node_modules` and reinstall everything.

**Comment by pwang2** [comment]
@chengzhuotc 
Brutal solution:
> rm -rf node_modules package-lock.json yarn.lock 
> npm  install # or yarn 

Soft solution:
> npm upgrade --depth=9999 @vue/component-compiler-utils

**Comment by liuhuidi** [comment]
还是不行啊，尤大婶

**Comment by pwang2** [comment]
`rm -rf package-lock.json node_modules`

**Comment by JesonRondo** [comment]
`nuxtjs` still doesn't work.... The same error with `prettier`

**Comment by lanxin1234** [comment]
you can try 
cd node_modules/
rm -rf _prettier@1.13.0@prettier
cnpm install prettier@~1.12.1

（if your node_modules/ have _prettier@1.13.0@prettier ）

**Comment by transtone** [comment]
@lanxin1234  no need install prettier-1.12.x. 
use npm replace cnpm, or wait taobao update component-compiler-utils-1.3.0 to 1.3.1

**Comment by 5amfung** [comment]
Yarn and npm registries are still pointing to 1.13.0, not 1.13.1.

**Comment by chengzhuotc** [comment]
![image](https://user-images.githubusercontent.com/9107399/40598256-366d02e4-6279-11e8-9533-f6e0ac3bee4c.png)我试了很多了，包也重新删除然后 cnpm install prettier@~1.12.1
  @还是出现这个问题

**Comment by JesonRondo** [comment]
@lanxin1234 it work with this manual install.
@transtone only `nuxt@1.4.0` has this error. It use `vue-loader@13.7.0`. But `nuxt@1.4.0` is the newest stable version....

**Comment by fyddaben** [comment]
@lanxin1234 是的，需要删掉，我是这样写的，成功了，感谢
```
rm -rf node_modules
cnpm cache verify
cnpm i
rm -rf node_modules/_prettier@1.13.0@prettier
cnpm install --save-dev prettier@1.12.0
```

**Comment by chengzhuotc** [comment]
难道就我一个人没有成功吗。各种方式都试了，还是不行

**Comment by momolizi** [comment]
上面的方法都试了，还是报错

**Comment by outstandinglife** [comment]
rm -rf node_modules npm install npm install prettier@~1.12.1
我的成功了

**Comment by superfff** [comment]
楼上我也是不行~

今天打算把线上的分支拉多一个到本地做迭代.
然后装完package就报错了.
旧的包是可以的.

我还以为是跟同事更新代码搞错了 - -

**Comment by qidaizhe11** [comment]
分享下，此官方修复只针对 vue-loader 15.x 版本，如果你项目引用的是 13.x/14.x等版本，与此修复无关，需升级 vue-loader 至 15.x版，

升级后需要注意不兼容更新：
https://vue-loader.vuejs.org/migrating.html#notable-breaking-changes

`// webpack.config.js
const VueLoaderPlugin = require('vue-loader/lib/plugin')

module.exports = {
  // ...
  plugins: [
    new VueLoaderPlugin()
  ]
}`

**Comment by outstandinglife** [comment]
rm -rf node_modules 
npm install  
rm -rf node_modules/_prettier@1.13.0@prettier
npm install prettier@~1.12.1
试试这样

**Comment by chengzhuotc** [comment]
这样做我还是没有成功一直在报错

**Comment by xiaofan9** [comment]
还是报错的兄弟有几个。。。

**Comment by xiaofan9** [comment]
window 10 下
cnpm i
rm node_modules/_prettier@1.13.0@prettier
输入 a 回车
cnpm i prettier@~1.12.1

**Comment by WormGirl** [comment]
我也是。。。

**Comment by tabqiang** [comment]
删 node_modules 
npm install 
npm run dev 
可以了

**Comment by yangguang111lll** [comment]
我也在报错

**Comment by yangguang111lll** [comment]
怎么做的？

**Comment by hejialianghe** [comment]
npm install prettier@~1.12.1  这个是可以的

**Comment by huyajie** [comment]
@chengzhuotc  升级完vue -loader 后    没有其他的报错吗？有解决吗

**Comment by liuhuidi** [comment]
目前没有其他保错，已解决，谢谢😘




| |
liuhuidi428
邮箱：liuhuidi428@163.com
|

签名由 网易邮箱大师 定制

在2018年05月28日 15:32，Ya jie 写道：

@chengzhuotc 升级完vue -loader 后 没有其他的报错吗？有解决吗

**Comment by anqing-kingjay** [comment]
为什么我npm install --save-dev prettier@1.12.1也会报错

**Comment by chengzhuotc** [comment]
@huyajie 
![image](https://user-images.githubusercontent.com/9107399/40602914-e15a06e4-628c-11e8-9e6d-0450b4adb3fe.png)这样做就好了

**Comment by yangguang111lll** [comment]
![default](https://user-images.githubusercontent.com/20963499/40602985-271e9140-628d-11e8-9a6b-1829b4f671bd.png) 还是不行

**Comment by chengzhuotc** [comment]
不知道是不是和node环境有关，我用的是10点几版本的，然后照着上面试了很多次不行，然后我吧vue-loader升级最新版本，
![image](https://user-images.githubusercontent.com/9107399/40602983-24f828d6-628d-11e8-826e-de955ddf2056.png)
在改下配置，然后照着上面降级就可以了

**Comment by blairzhao111** [comment]
用的是 vue 2.3.0 和 vue -loader 14.2.1, 删了node_modules后重新npm install后还是报错；但手动install 1.12.1 版本的 prettier 就可以了

**Comment by xuebingwang** [comment]
作为一个node小白，这问题我也弄了一个多小时，最先还以为我哪里代码写错了，查了一通才查到这里，谷歌真牛掰，这个issue10几个小时提的，谷歌就能搜出来了。

顺便鄙视一下百度

**Comment by yangguang111lll** [comment]
难道这问题作者没关注么？

**Comment by tianxiaofeng747** [comment]
用 vue init 生成新项目，竟然报错， 好神奇啊。。。

**Comment by yangguang111lll** [comment]
感觉没权威性啊，老报错。。。

**Comment by yangguang111lll** [comment]
@tianxiaofeng 报错啊

**Comment by tianxiaofeng747** [comment]
@yangguang111lll  我也报错， 老项目可以的。 奇怪。

**Comment by luanwulin** [comment]
nuxt项目解决了
在推送服务器上，装完依赖过后，手动单独安装一次prettier就好了
![image](https://user-images.githubusercontent.com/16553854/40603571-e180df4c-628e-11e8-8d1a-de2d3b24c374.png)

**Comment by xiaofan9** [comment]
@yangguang111lll 
window 10 下

cnpm i
rm node_modules/_prettier@1.13.0@prettier
// 输入 a 回车
cnpm i prettier@~1.12.1 -D

**Comment by jkf8x8** [comment]
试了4个小时，，试光了所有方法。。绝望

**Comment by hlg-facai** [comment]
心累

**Comment by ChenArno** [comment]
I can't me too

**Comment by liuhuidi** [comment]
🐣👏🏻👑给你，心累拿走！谢谢！




| |
liuhuidi428
邮箱：liuhuidi428@163.com
|

签名由 网易邮箱大师 定制

在2018年05月28日 16:16，hlg-facai 写道：

心累

**Comment by momolizi** [comment]
为什么我用npm下载包可以，用yarn就不行了

**Comment by gracelinmumu** [comment]
prettier@1.12.1版本，yarn不行，npm i OK

**Comment by ChenArno** [comment]
mac 下各种不行，什么时候能修复，init就可以

**Comment by 13463736868** [comment]
对于13.X 的 可以 
删除node_modules下的_prettier@1.13.0执行cnpm install --save-dev prettier@1.12.0好用

**Comment by ChenArno** [comment]
还是不行，

**Comment by WormGirl** [comment]
把所有依赖装好，然后cnpm install prettier@1.12.1,然后重启如果还是不行打开node_modules找到prettier@1.12.1、prettier@1.13.1，把prettier@1.13.1删掉就好了

**Comment by stardew516** [comment]
1. 先要升级vue-loader版本
npm install --save-dev vue-loader@15.2.1
2. 删除node_modules
rm -rf node_modules
3. 重新加载依赖（淘宝镜像快一点）
cnpm install
4. prettier降级
cnpm install prettier@~1.12.1

**Comment by ChenArno** [comment]
可以了，原来node_modules 下面有那么多prettier版本，这个bug还是尽早修复吧

**Comment by luanwulin** [comment]
已经清除了yarn缓存
yarn cache clean
依然不能通过prettier@1.12.1解决，
npm就可以

**Comment by hardikshah91** [comment]
Still having an issue on Nuxtjs
version: 
"nuxt": "^1.0.0", 
"prettier": "^1.12.1"

**Comment by suncunhu** [comment]
这个问题浪费了很多人的时间啊 。。。。

**Comment by WormGirl** [comment]
有没有人能说一下这个产生的具体原因，对于旧的项目没有上传node_modules,如果现在install是不是都会出这个问题，感觉现在的解决方法不能解决根本问题

**Comment by royalrover** [comment]
这个直接影响线上项目迭代了，到底是什么问题导致的？

**Comment by sxyseo** [comment]
In prettier 1.13.0, default parser was removed with a minor version(used to be babylon), this breaks the formatter here.
是在prettier的 1.13.0版本，默认的一个解析器被移除了导致项目创建失败？

这个影响比较大啊。
弄了半天才正常跑起来。

踩坑日志 https://www.whatled.com/post-6206.html

**Comment by azz** [comment]
@yyx990803 Want to lock this, edit the original post to say run:

```bash
npm update --depth=9999 @vue/component-compiler-utils
```
?

**Comment by Baoyx007** [comment]
如果用 `yarn`, 可以在项目的 package.json 中添加:

 "resolutions":{
    "vue-loader/prettier": "1.12.1"
  },

**Comment by caszhou** [comment]
For nuxt@1.4.0

- npm i prettier@~1.12.1
- rm -rf node_modules/
- npm i

works

**Comment by pwang2** [comment]
UPDATE:  **NO need to do downgrade prettier version now, this was working as workaround before release of @vue/component-compiler-utils 1.3.1**

If you have applied downgrade above, remove it from pacakge.json then run 
```
npm update --depth=9999 @vue/component-compiler-utils
```

if havn't,  just run 
```
npm update --depth=9999 @vue/component-compiler-utils
```

**Comment by hu-qi** [comment]
我试着 
`npm install prettier@~1.12.1 . `
就ok了
