### ISSUE TITLE
Is tsc compile error in @vue/component-compiler-utils/dist/index.js ??

### ISSUE THREAD

**Issue by crsGyj2017** [vuejs/component-compiler-utils#20]
![image](https://user-images.githubusercontent.com/33442715/40953461-64462d96-68b2-11e8-8978-a87c644178fb.png)
![image](https://user-images.githubusercontent.com/33442715/40953476-716dd2ee-68b2-11e8-9a78-693854b093a7.png)

**Comment by yyx990803** [comment]
The type exports are not in emitted JS...
