### ISSUE TITLE
The `preprocessOptions` can not work when using `less`

### ISSUE THREAD

**Issue by JunreyCen** [vuejs/component-compiler-utils#24]
```javascript
// styleProcessors/index.ts
const less = {
  render(
    source: string,
    map: any | null,
    options: any
  ): StylePreprocessorResults {
    const nodeLess = require('less')

    let result: any
    let error: Error | null = null
    nodeLess.render(
      source,
      { syncImport: true },
      (err: Error | null, output: any) => {
        error = err
        result = output
      }
    )

    if (error) return { code: '', errors: [error] }

    if (map) {
      return {
        code: result.css.toString(),
        map: merge(map, result.map),
        errors: []
      }
    }

    return { code: result.css.toString(), errors: [] }
  }
}
```
Here, this `options` is not used in `nodeLess.render`, when i want to assign the `paths` param in `render` function.

**Comment by znck** [comment]
As far as I know,`vue-loader` is not using style preprocessor features of `component-compiler-utils`, it uses loader chain for preprocessing style blocks.

In other environment (rollup, jest, parcel), WebpackFileManager is not a thing so merging options should not pose any issues.

**Comment by JunreyCen** [comment]
I use node/gulp to compile sfc instead of webpack since i don't want to bundle the dependence...btw, thanks to fix this problem
