### ISSUE TITLE
VueJS not rendering component on jquery ajax load

### ISSUE THREAD

**Issue by rajvinoth227** [vuejs/component-compiler-utils#44]
I have html via AJAX call which contain components. my problem is component-a is not rending, is it possible in jquery ajax load? i tried vm.compile() and vm.$forceUpdate() on .load callback but nothing happens.

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

**Comment by rajvinoth227** [comment]
Thanks for your reply..If you have any idea about this issues let me know
