### ISSUE TITLE
Is the version of prettier necessary to be locked?

### ISSUE THREAD

**Issue by meteorlxy** [vuejs/component-compiler-utils#69]
I just made a tool to make prettier works better with Vue SFC, which depends on `@vue/component-compiler-utils`.

I encountered an error when trying to resolve prettier's [sharable config](https://prettier.io/docs/en/configuration.html#sharing-configurations). I noticed that this feature was released in [prettier v1.17.0](https://prettier.io/blog/2019/04/12/1.17.0.html#config), and my prettier is v1.18.x.

But when I inspected the lock file, I found that `@vue/component-compiler-utils` is using `prettier` as a denpendency, too, and locks the version to `1.16.3`, which caused this error.

https://github.com/vuejs/component-compiler-utils/blob/37b4a6a99ecaa8bf27c777191ac17e9168c70cd1/package.json#L61

Is the version of prettier necessary to be locked to 1.16.3?

**Comment by Justineo** [comment]
See https://github.com/vuejs/component-compiler-utils/issues/55

**Comment by meteorlxy** [comment]
Alright, got it.
