### ISSUE TITLE
[Feature Request] Bump prettier version

### ISSUE THREAD

**Issue by meteorlxy** [vuejs/component-compiler-utils#70]
Related issues:
- #55 
- #69 

Sorry for openning another issue, but I cannot get rid of the version inconsistency of `prettier`... 😢 

![image](https://user-images.githubusercontent.com/18205362/62515288-83d44100-b854-11e9-9dc1-cc7cab236c29.png)

I know that could be an issue of `yarn`, but it would be better if we can bump the version of prettier...

**Comment by mariusa** [comment]
A compiler shouldn't depend on code formatting / beautifier utilities. That's the job of the IDE. vscode already handles this very well, for example.

Would you please remove prettier dependency?

**Comment by sodatea** [comment]
Bumped at v3.0.1
