### ISSUE TITLE
Vue loader breaks with version 3.0.1

### ISSUE THREAD

**Issue by milewski** [vuejs/component-compiler-utils#73]
version `v3.0.1` is missing the lib folder, which causes:

```
node_modules/vue-loader/lib/index.d.ts:2:37 - error TS2307: Cannot find module '@vue/component-compiler-utils/lib/types'.

2 import { VueTemplateCompiler } from '@vue/component-compiler-utils/lib/types'
```

**Comment by sodatea** [comment]
It's `vue-loader` that has referred to the wrong entry, actually.
But I've released a new version to fix it anyway, in case any other downstream libraries made the same mistake.
