### ISSUE TITLE
TypeError: Class constructor LRUCache cannot be invoked without 'new'

### ISSUE THREAD

**Issue by markuzzi** [vuejs/component-compiler-utils#79]
With LRUCache updated to version 5.1.1, the vue component compiler utils throw the error
`TypeError: Class constructor LRUCache cannot be invoked without 'new'`

I think this is due to line 9 in lib/parse.ts:
```
const cache = require('lru-cache')(100)`;
```

If this would be changed to 
```
const LRUCache = require('lru-cache');
const cache = LRUCache(100);
```
I think this would fix the problem.

Does it make sense?

**Comment by sodatea** [comment]
This project depends on `lru-cache` v4 at the moment. PR's welcome.

**Comment by lenkog** [comment]
PR: https://github.com/vuejs/component-compiler-utils/pull/83
