### ISSUE TITLE
Provide installation instructions on missing language preprocessors

### ISSUE THREAD

**Issue by znck** [vuejs/component-compiler-utils#8]
If a template is using `pug` syntax and `pug` package is not installed, it fails. There should be graceful warning explaining what failed and how to resolve it.

For example:

> Component `Example.vue` uses lang `pug` for template. Please install the language preprocessor.
> 
> $ npm add -D pug

**Comment by mikemenaker** [comment]
@znck I'm working on this issue and think I have a solution, I tried to create a branch (to make sure I'm on the right track) but don't have access.

Should I fork it then create a branch off of that or what's the protocol?

Thanks.

**Comment by mikemenaker** [comment]
PR: https://github.com/vuejs/component-compiler-utils/pull/10

**Comment by mikemenaker** [comment]
@znck not sure if you get notifications on PR updates, but I pushed a commit yesterday to address your feedback.

**Comment by LinusBorg** [comment]
This got merged so the issue can be closed?
