### ISSUE TITLE
Switch `prettier` to an optional- or peerDependency

### ISSUE THREAD

**Issue by sirlancelot** [vuejs/component-compiler-utils#84]
With the release of Prettier v2.x, projects wishing to update to the latest version will download *both* versions of Prettier due to this module having a hard dependency on v1.x.

Since Prettier is only `require`'d when `prettify == true` and `NODE_ENV != "production"`, can this dependency be switched to an optionalDependency or peerDependency? Or perhaps its version requirement relaxed to include v2.x?

**Comment by P4sca1** [comment]
Totally agree with that. Currently this causes problems in my workspace, because yarn keeps placing a version < 2.0.0 in the .bin folder, even though I have listed prettier 2.0.4 in my dependencies.

**Comment by sodatea** [comment]
- Making it a peer dependency ❌ This would a breaking change
- Relaxing the version requirement to 2.x ❌ This would break Node.js 8.x users
- Making it an optional dependency ✅ This would be mostly fine

---

> Currently this causes problems in my workspace

To be fair, it is Yarn that causes the problem, not this package.
